//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posible_parcial_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        public int IDViaje { get; set; }
        public int IDvehiculo { get; set; }
        public int IDpasajero { get; set; }
        public string Destino { get; set; }
        public int Kilometro { get; set; }
        public int Importe { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Pasajero Pasajero { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
